CREATE TABLE if not exists Users (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(30), surname VARCHAR(30), email VARCHAR(50), birthday TIMESTAMP);

CREATE TABLE if not exists UserConfig (id INTEGER PRIMARY KEY AUTOINCREMENT, userId INTEGER, score INTEGER);

ALTER TABLE UserConfig ADD COLUMN avatarId INTEGER;